<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Necesar pentru SignInManager<T> folosit in AuthService -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AirlineFlightManagement.DataAccess\AirlineFlightManagement.DataAccess.csproj" />
    <ProjectReference Include="..\AirlineFlightManagement.Models\AirlineFlightManagement.Models.csproj" />
  </ItemGroup>

</Project>
